insert into alumno (nombre) values ("Roberto");
insert into alumno (nombre) values ("Pedro");
insert into alumno (nombre) values ("Manuela");
insert into alumno (nombre) values ("Carlos");
insert into curso (denominacion) values ("dibujo");
insert into curso (denominacion) values ("musica");
insert into curso (denominacion) values ("fotografia");
insert into alumnocurso (fecha, idalumno, idcurso) values ('2018-10-10',1,1);
insert into alumnocurso (fecha, idalumno, idcurso) values ('2018-10-5',1,2);
insert into alumnocurso (fecha, idalumno, idcurso) values ('2018-10-12',4,2);
insert into alumnocurso (fecha, idalumno, idcurso) values ('2018-11-8',3,2);